---
- name: create app directory
  file:
    path={{ web_app_path }}/{{ item }}
    state=directory
    mode=0755
    owner={{ web_owner }}
    group={{ web_group }}
  with_items:
    - .
    - src
    - run
    - log
    - env
  sudo: yes

- name: deploy app src
  copy:
    src=./
    dest={{ web_app_path }}/src/
    owner={{ web_owner }}
    group={{ web_group }}
  sudo: yes

- name: deploy app src
  template:
    src=wxapp.py
    dest={{ web_app_path }}/src/
  sudo: yes

- name: Install the uwsgi app configuration file
  template:
    src=uwsgi-wxapp.ini
    dest={{ web_app_path }}/src/uwsgi.ini
    owner={{ web_owner }}
    group={{ web_group }}
  sudo: yes

- name: install dependencies into virtualenv
  pip:
    requirements={{ web_app_path }}/src/requirements.txt
    virtualenv={{ web_app_path }}/env
    state=present
  sudo: yes

- name: create supervisor program config for [uwsgi]
  template:
    src=uwsgi-wxapp.conf
    dest=/etc/supervisor/conf.d/uwsgi-wxapp.conf
  notify:
    - restart app
  sudo: yes

- name: create nginx site config
  template:
    src=nginx-wxapp.conf
    dest=/etc/nginx/sites-available/nginx-wxapp.conf
  sudo: yes

- name: link nginx config
  file:
    src=/etc/nginx/sites-available/nginx-wxapp.conf
    dest=/etc/nginx/sites-enabled/nginx-wxapp.conf
    state=link
  notify:
    - restart nginx
  sudo: yes

- name: remove forward in /etc/ufw/before.rules
  blockinfile:
    dest: /etc/ufw/before.rules
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    content: ""

- name: insert forward in /etc/ufw/before.rules
  blockinfile:
    dest: /etc/ufw/before.rules
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    content: |
      # NAT Table rules
      *nat
      :PREROUTING ACCEPT [0:0]
      :POSTROUTING ACCEPT [0:0]
      :OUTPUT ACCEPT [0:0]
      # Forward traffic coming from eth0 (internet) to port 80 send to {{ app_port }} for processing
      -A PREROUTING -i eth0 -p tcp -m tcp --dport 80 -j REDIRECT --to-port {{ app_port }}
      #-A PREROUTING -i eth0 -p tcp -m tcp --dport 443 -j DNAT --to-destination 192.168.1.2
      # any traffic leaving eth0 from private land apply NAT Masquerade
      #-A POSTROUTING -o eth0 -s 192.168.1.0/24 -j MASQUERADE
      # don't delete the 'COMMIT' line or these nat table rules won't be processed
      COMMIT
  notify:
    - reload ufw
  sudo: yes
